app/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('filter/', views.filter, name='filter'),
    path('product/', views.product, name='product'),
    

]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

goods/models.py
from django.db import models

# Create your models here.

goods/views.py
from django.shortcuts import render



def catalog(request):
    return render(request, 'goods/catalog.html')


def filter(request):
    return render(request, 'goods/filter.html')

def product(request):
    return render(request, 'goods/product.html')
#fsdfedgdrgergergre

main/views.py
from django.http import HttpResponse
from django.shortcuts import render



def index(request):
    context = {
        'title':'Главная страница',
    }

    return render(request, 'main/index.html',context)


def about(request):
    context = {
        'title':'Страница о нас',
    }

    return render(request, 'main/about.html',context)
# Create your views here.

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}Каталог{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'catalog/css/catalog.css' %}">
{% endblock %}


{% block body %}
<div class="catalog-header">
    <div class="catalog-header-item">
        
    </div>
</div>

<div class="catalog-menu">
  <H3>Каталог</H3>
</div>

<div class="catalog-items">


  {% for el in goods %}
    
      <div class="catalog-item">
        <a href="{% url 'catalog:product' el.slug %}">
        {% if el.discount %}
          <span class="badge bg-warning text-dark">Скидка {{el.discount}} %</span>
        {% endif %}
        <div class="item-image">
          {% if el.image %}
            <img src="{{ el.image.url }}" alt="{{ el.name }}">
          {% else %}
            <img src="{% static 'all/notfound.jpg' %}" alt="image not found">
          {% endif %}
        </div>
        <div class="description">
          <h5>{{el.name}}</h5>
          <p class="product_id">id: {{ el.display_id }}</p>
  
  
          <div class="product_bottom">
            {% if el.discount %}
              <p style="display: inline;"><s>{{el.price}}</s>СУМ</p>
              <p style="display: inline;"><strong>{{el.sell_price }}00 СУМ</strong></p>
  
            {% else %}
              <p><strong>{{el.price}} СУМ</strong></p>
            {% endif %}
  
            <div class="star">
              <i class="fa-solid fa-star" style="color: #FFD43B;"></i>
              <h6>4.9</h6><h6 style="color: rgb(91, 91, 91);">10 оценок</h6>
            </div>
          </a>
            <button class="btn">Купить</button>
          </div>
          
        </div>
      </div>
    
  {% endfor %}

</div>




{% endblock %}

{% block footer %}
{% include "main/footer.html" %}
{% endblock footer %}

goods/templates/goods/filter.html
{% extends "main/base.html" %}
{% load static %}
{% comment %} {% load goods_tags %} {% endcomment %}

{% block title %}Каталог{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'catalog/css/filter.css' %}">
{% endblock %}





{% block body %}



<div class="main">

    <ul>
        {% comment %} {% tag_categories as categories %}
        {% for category in categories %}
        <a href="{% url "catalog:catalog" category.slug %}">
            <li>
                <img src="{% static 'all/notfound.jpg' %}" alt="img not found" class="img">
                <h4>{{category.name}}</h4>
            </li>
        </a>
        {% endfor %} {% endcomment %}
        <a href="{% url "goods:index" %}">
            <li>a</li>
        </a><a href="{% url "goods:index" %}">
            <li>b</li>
        </a>
        <a href="{% url "admin:index" %}">
            <li><h4>Админ панель</h4></li>
        </a>
    </ul>

</div>


{% endblock %}










{% block footer %}
{% include "main/footer.html" %}
{% endblock footer %}

goods/templates/goods/product.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}
{% block style %}
  <link rel="stylesheet" href="{% static 'catalog/css/product.css' %}" />
{% endblock %}

{% block body %}
  <div class="product">
    <div class="product-header">
        <div class="e"></div>
      <div class="_header">
        <a href="{% url 'catalog:catalog' %}" class="back"><h1><</h1></a>
        <div class="opisanye"></div>
        <div class="izbr">
          <a href="#" class="back"><i class="fa-regular fa-heart"></i></a>
          <a href="#" class="back"><i class="fa-solid fa-share-nodes"></i></a>
        </div>
      </div>
      <script src="{% static 'catalog/js/product.js' %}"></script>
      <div class="product-image">
        {% if product.image %}
          <img src="{{ product.image.url }}" alt="{{ product.name }}" />
        {% else %}
          <img src="{% static 'all/notfound.jpg' %}" alt="image not found" />
        {% endif %}
      </div>
    </div>
    {% comment %} product body {% endcomment %}
    <div class="product-body">
      <h1> {{product.name}} </h1>
    </div>
  </div>
{% endblock %}
{% block footer %}
  {% include 'main/footer.html' %}
{% endblock %}

main/templates/main/about.html
{% extends "main/base.html" %}

{% block style %}
{% endblock %}


{% block body %}
<h1>О нас</h1>
<p>hello world</p>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>{{title}}</title>
    <link rel="shortcut icon" href="{% static 'all/logo.jpg' %}" type="image/x-icon" style="border-radius: 100%;">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block style %}{% endblock %}
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <style>
        .foort{
            width: 100%;
            color: rgba(255, 255, 255, 0);
            margin: 100px 0;
        }
    </style>

</head>
<body>
{% block nav %}{% endblock nav %}
<main>
    {% block body %}
    {% endblock %}
</main>


<div class="foort">1</div>
{% block footer %}{% endblock footer %}
</body>
</html>

main/templates/main/footer.html
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'main/css/footer.css' %}">
{% endblock %}

<footer class="row _footer">
     <div class="col"><a href="{% url "main:index" %}"><i class="fa-solid fa-house" style="color: #a2a2a2;"></i>
    <p>Главная</p></a></div>
    <div class="col"><a href="{% url "goods:filter" %}"><i class="fa-regular fa-chart-bar" style="color: #a2a2a2;"></i>
    <p>Каталог</p></a></div> 
    <div class="col"><a href="#"><i class="fa-solid fa-cart-shopping" style="color: #a2a2a2;"></i>
    <p>Корзина</p></a></div>
    <div class="col"><a href="#"><i class="fa-regular fa-heart" style="color: #a2a2a2;"></i>
    <p>Избранное</p></a></div>
    <div class="col"><a href="#"><i class="fa-regular fa-user" style="color: #a2a2a2;"></i>
    <p>Профиль</p></a></div>
</footer>

main/templates/main/index.html
{% extends "main/base.html" %}



{% block nav %}
{% include 'main/nav.html' %}
{% endblock nav %}



{% block body %}

<h1>Главная страница</h1>



{% endblock %}

{% block footer %}
{% include 'main/footer.html' %}
{% endblock footer %}

main/templates/main/nav.html
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'main/css/header.css' %}">
{% endblock %}

<header class="row">
    <div class="col location log">
        <div><a href="#"><i class="fa-solid fa-location-dot"></i></a></div>
    </div>
    <div class="col-8 logo">
        <a href="#"><img src="{% static 'main/img/logo.png' %}"  alt="logo"></a>
    </div>  
    <div class="col search log">
        <div><a href="#" class="col"><i class="fa-solid fa-magnifying-glass"></i></a></div>
    </div>

</header>